### PR TITLE
[WIP] Portable Class Library Support

### LINKED ISSUE #4: Making the NuGet package to support multiple .NET versions
Currently the ColorSharp's NuGet package only supports .NET 4.0.

It's easy to support another .NET version, but supporting multiple versions at the same time without MS Visual Studio isn't trivial.

It would be nice to have this feature to make easier to use ColorSharp.

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #4

I've not had a chance to test this out thoroughly, but I believe this is the easiest approach to supporting multiple versions of the .NET Framework in your project - as you don't have to manage references to framework assemblies.

This requires the latest version of VS2013, but should work against the Community SKU.

 - [x] switch main project over to Portable Class Library (targeting .NET 4, Windows 8, Silverlight 5, WP 8.1 and Windows Phone Silverlight 8.1 (?!?!)
 - [x] update package generation to use new project
 - [x] verify package outputs binary at `portable-net40%2Bsl50%2Bwin%2Bwpa81%2Bwp80`
 - [x] test this against [Community Edition of VS2013](http://www.visualstudio.com/en-us/news/vs2013-community-vs.aspx)
 - [x] fix up AppVeyor CI issue

Questions:

 - [ ] what sort of Mono support did you have in mind here? what should I be testing to confirm all is well?
 - [ ] how should I test this against the existing NUnit test suite? Will any test runner do?

Let me know if you have any questions or concerns on this.

### CODE REVIEW

**Comment by castarco** [comment]
Hi, I'll review this pull request in a few hours :) , thanks for your contribution.

The AppVeyor CI issue is my fault, it's not properly configured, I have to fix it.

**Comment by shiftkey** [comment]
@castarco Seems the script I added did enough to make it pass - let me know if there's anything else to add

**Comment by castarco** [comment]
Sorry for being slow, I haven't find time to check it. I've seen the changes and look good, but I didn't test it yet.

I have two doubts. Many months ago I tried to use PCLs, but I had problems on Linux :( . I suppose I can check if the problems persist with new Mono versions when I test it.

The other doubt is about other .NET versions support. I've also had problems trying to use a signed version of ColorSharp compiled for .NET 4.0 on a .NET 4.5 project . I'm not an expert, it's possible in theory to use signed 4.0 assemblies on 4.5 projects?

I

**Comment by shiftkey** [comment]
> I suppose I can check if the problems persist with new Mono versions when I test it

I think this depends on your setup. For example, Ubuntu 14.04 (Trusty Tahr) supports Mono 3.2.8, but you can grab Mono 3.12 direct from the project. And there's a big difference between them.

> I want to support Mono >= 3.12 , on Linux, Mac & Windows.

I think this is a good benchmark to aim for. I've not tried wiring up Travis to do mono builds for each platform, maybe it's possible?

>  I've also had problems trying to use a signed version of ColorSharp compiled for .NET 4.0 on a .NET 4.5 project .

I could ramble on a lot about the *actual* value of signed assemblies and the scenarios where this is required (tl;dr: it's rather narrow). Unless you're dealing with scenarios were multiple instances of your assembly can exist in the same AppDomain (for example, Visual Studio extensions), I wouldn't stress too much about needing to sign your assemblies.

> The PCL 328 is for .NET 4.0 and other mobile platforms, but the description says nothing about 4.5 .

4.5 is considered an in-place replacement for 4.0, so a 4.0 assembly should run without issue on a machine which has .NET 4.5 installed. There's a whole bunch of other details about how the Mono runtime works which I'd need to wrap my head around as well, but I'd love to hear more about the problem you had, and if you can recreate it again that'd be amazing!

**Comment by akoeplinger** [comment]
> 1.I'll be following this other issue too ( travis-ci/travis-ci#3036 ) , it seems that there are problems with PCLs on Linux.

The PCL reference assemblies package was installed on the Travis workers so it should just work. You can install it on your machine with `sudo apt-get install referenceassemblies-pcl` when you're using the Xamarin/Mono repository.

**Comment by shiftkey** [comment]
Was able to clone and run the tests in Visual Studio Community Edition (after installing the NUnit test runner). Haven't had a chance to look into the Mono questions raised here...

**Comment by aloisdg** [comment]
Hello,

Any news around the publication of a PCL?
Thank you,

Cheers!

**Comment by castarco** [comment]
Hello @aloisdg , I paused the development of ColorSharp because I was a little bit discouraged after many problems with Mono, but it seems that the liberation of the .NET source code improved the situation. This afternoon I'll revisit the problem and I'll try to release a PCL version of the library.

Thank you for your interest.

**Comment by aloisdg** [comment]
Hi @castarco , thank you for your implication! :)

**Comment by shiftkey** [comment]
Closing this one out as it's totally neglected now (my fault) but I'll leave the branch open if someone wants to pick this up.

**Pull request closed without merging**
